# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# To get proper caching for monorepos we use actions/cache@eb78578266b7cec649ab65b6f1534bd6040c838b (from master branch) 
# instead of actions/cache@1. Support for monorepos will be available in actions/cache@2.

name: Test Package
on: [pull_request]

jobs:
  dependencies:
    strategy:
      matrix:
        # Run tests with all of these node versions/systems :]
        node-version: [10.x]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    name: Learna with Node ${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      # Check out code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup Learna cache
      - name: restore lerna
        id: learna-cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/build
            */*/node_modules
          key: n-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
      # Run yarn and learna to build packages
      - name: Bootstrap 
        # Optionally skip running bootstrap if the cache is configured
        if: steps.learna-cache.outputs.cache-hit != 'true'
        run: yarn bootstrap


  test:
    strategy:
      matrix:
        package: [json-file]
        # Run tests with all of these node versions/systems :]
        node-version: [10.x]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    # needs: dependencies
    name: ${{ matrix.package }} with Node ${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      # Check out code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup Learna cache
      - name: restore lerna
        id: learna-cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/build
            */*/node_modules
          key: n-${{ runner.os }}-${{ node-version }}-${{ hashFiles('yarn.lock') }}
      # Run yarn and learna to build packages
      - run: Bootstrap 
        # Optionally skip running bootstrap if the cache is configured
        if: steps.learna-cache.outputs.cache-hit != 'true'
        run: yarn bootstrap

      # Test package
      - name: Test ${{ matrix.package }}
        run: cd packages/${{ matrix.package }} && "$GITHUB_WORKSPACE/scripts/module-scripts-check-packages.sh"
        env:
          CI: true
